name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Install
      working-directory: ./web
      run: npm install
      
    - name: Build
      working-directory: ./web
      run: |
        npm run build
    
    - run: mkdir -p dist
    - run: echo hello > dist/*
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: dist


