name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Install
      working-directory: ./web
      run: npm install
      
    - name: Build
      working-directory: ./web
      run: |
        npm run build
    
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
          name: dist
          path: web/dist

